import { AppProps } from 'next/app';
import Head from 'next/head';
import '../styles/globals.css';

function MyApp({ Component, pageProps }:AppProps):JSX.Element {
  return (
    <>
     <Head>
        <title>MyTop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,500;0,600;0,700;1,200&display=swap" rel="stylesheet"/>
      </Head>
    <Component {...pageProps} />
    </>
  )
  
}

export default MyApp;
